<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllPosts()
    {
        return $this->createQueryBuilder('a')
            ->addOrderBy('a.createdAt', 'DESC')
            ->leftJoin('a.author', 'author')
            ->addSelect('author')
            ->getQuery();
    }

    public function allArticles()
    {
        return $this->queryAllPosts()->execute();
    }

}
