<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPosts()
    {
        $qb = $this->createQueryBuilder('a')
            ->addOrderBy('a.titulo', 'DESC')
            ->leftJoin('a.mensaje', 'mensaje')
            ->addSelect('a.mensaje')
            ->getQuery()
        ;
        return $qb->execute();
    }
}
